language: php
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

## PHP versions we test against
php:
  - 7.0
  - 7.1
  - nightly

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 7.0
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: nightly
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest

## Install or update dependencies
install:
  - if [ -z "$dependencies" ]; then composer install --prefer-dist; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --prefer-dist -n; fi;
  - composer show

## Run the actual test
script: make travis

## Gather coverage and set it to coverage servers
after_script: make travis-coverage
